(function () {
  "use strict";

  window.siteCatalog = {
    searchEngines: [
      {
        id: "baidu",
        name: "百度",
        icon: "./assets/search-icons/baidu.ico",
        badge: "百",
        badgeColor: "#ffffff",
        badgeBackground: "#4e6ef2",
        homeUrl: "https://www.baidu.com/",
        searchUrl: "https://www.baidu.com/s?ie=utf-8&wd={query}",
      },
      {
        id: "google",
        name: "谷歌",
        icon: "./assets/search-icons/google.ico",
        badge: "G",
        badgeColor: "#ffffff",
        badgeBackground: "#4285f4",
        homeUrl: "https://www.google.com/",
        searchUrl: "https://www.google.com/search?q={query}",
      },
      {
        id: "bing",
        name: "必应",
        icon: "./assets/search-icons/bing.ico",
        badge: "B",
        badgeColor: "#ffffff",
        badgeBackground: "#008373",
        homeUrl: "https://www.bing.com/",
        searchUrl: "https://www.bing.com/search?q={query}",
      },
      {
        id: "so",
        name: "360",
        icon: "./assets/search-icons/so.png",
        badge: "360",
        badgeColor: "#ffffff",
        badgeBackground: "#19b955",
        homeUrl: "https://www.so.com/",
        searchUrl: "https://www.so.com/s?q={query}",
      },
      {
        id: "duckduckgo",
        name: "DuckDuckGo",
        icon: "./assets/search-icons/duckduckgo.png",
        badge: "D",
        badgeColor: "#ffffff",
        badgeBackground: "#de5833",
        homeUrl: "https://duckduckgo.com/",
        searchUrl: "https://duckduckgo.com/?q={query}",
      },
      {
        id: "sogou",
        name: "搜狗",
        icon: "./assets/search-icons/sogou.ico",
        badge: "搜",
        badgeColor: "#ffffff",
        badgeBackground: "#ff6347",
        homeUrl: "https://www.sogou.com/",
        searchUrl: "https://www.sogou.com/web?query={query}",
      },
      {
        id: "zhihu",
        name: "知乎",
        icon: "./assets/search-icons/zhihu.ico",
        badge: "知",
        badgeColor: "#ffffff",
        badgeBackground: "#1772f6",
        homeUrl: "https://www.zhihu.com/",
        searchUrl: "https://www.zhihu.com/search?type=content&q={query}",
      },
      {
        id: "youdao",
        name: "有道",
        icon: "./assets/search-icons/youdao.png",
        badge: "有",
        badgeColor: "#ffffff",
        badgeBackground: "#e74c3c",
        homeUrl: "https://www.youdao.com/",
        searchUrl: "https://www.youdao.com/result?word={query}&lang=zh-CN",
      },
      {
        id: "bilibili",
        name: "B站",
        icon: "./assets/search-icons/bilibili.ico",
        badge: "B",
        badgeColor: "#ffffff",
        badgeBackground: "#00aeec",
        homeUrl: "https://www.bilibili.com/",
        searchUrl: "https://search.bilibili.com/all?keyword={query}",
      },
      {
        id: "csdn",
        name: "CSDN",
        icon: "./assets/search-icons/csdn.ico",
        badge: "C",
        badgeColor: "#ffffff",
        badgeBackground: "#fc5531",
        homeUrl: "https://www.csdn.net/",
        searchUrl: "https://so.csdn.net/so/search?q={query}",
      },
      {
        id: "github",
        name: "GitHub",
        icon: "./assets/search-icons/github.svg",
        badge: "GH",
        badgeColor: "#ffffff",
        badgeBackground: "#24292f",
        homeUrl: "https://github.com/",
        searchUrl: "https://github.com/search?q={query}",
      },
      {
        id: "stackoverflow",
        name: "Stack Overflow",
        icon: "./assets/search-icons/stackoverflow.ico",
        badge: "SO",
        badgeColor: "#ffffff",
        badgeBackground: "#f48024",
        homeUrl: "https://stackoverflow.com/",
        searchUrl: "https://stackoverflow.com/search?q={query}",
      },
      {
        id: "google-scholar",
        name: "谷歌学术",
        icon: "./assets/search-icons/google-scholar.ico",
        badge: "学",
        badgeColor: "#ffffff",
        badgeBackground: "#4285f4",
        homeUrl: "https://scholar.google.com/",
        searchUrl: "https://scholar.google.com/scholar?q={query}",
      },
      {
        id: "baidu-scholar",
        name: "百度学术",
        icon: "./assets/search-icons/baidu-scholar.ico",
        badge: "百",
        badgeColor: "#ffffff",
        badgeBackground: "#5c78ff",
        homeUrl: "https://xueshu.baidu.com/",
        searchUrl: "https://xueshu.baidu.com/s?wd={query}",
      },
      {
        id: "semantic-scholar",
        name: "Semantic Scholar",
        icon: "./assets/search-icons/semantic-scholar.ico",
        badge: "SS",
        badgeColor: "#ffffff",
        badgeBackground: "#1857b6",
        homeUrl: "https://www.semanticscholar.org/",
        searchUrl: "https://www.semanticscholar.org/search?q={query}",
      },
    ],

    categories: [
      {
        name: "AI · 开发",
        links: [
          { name: "DeepSeek", url: "https://chat.deepseek.com/" },
          { name: "豆包", url: "https://www.doubao.com/" },
          { name: "通义千问", url: "https://tongyi.aliyun.com/qianwen/" },
          { name: "Kimi", url: "https://www.kimi.com/" },
          { name: "智谱清言", url: "https://chatglm.cn/" },
          { name: "文心一言", url: "https://yiyan.baidu.com/" },
          { name: "腾讯元宝", url: "https://yuanbao.tencent.com/" },
          { name: "讯飞星火", url: "https://xinghuo.xfyun.cn/" },
          { name: "魔搭社区", url: "https://www.modelscope.cn/" },
          { name: "阿里云百炼", url: "https://bailian.console.aliyun.com/" },
          { name: "ChatGPT", url: "https://chatgpt.com/" },
          { name: "Claude", url: "https://claude.ai/" },
          { name: "Gemini", url: "https://gemini.google.com/" },
          { name: "GitHub", url: "https://github.com/" },
          { name: "GitLab", url: "https://gitlab.com/" },
          { name: "Gitee", url: "https://gitee.com/" },
          { name: "Vercel", url: "https://vercel.com/" },
          { name: "Stack Overflow", url: "https://stackoverflow.com/" },
          { name: "MDN", url: "https://developer.mozilla.org/zh-CN/" },
          { name: "npm", url: "https://www.npmjs.com/" },
          { name: "CodePen", url: "https://codepen.io/" },
          { name: "Can I use", url: "https://caniuse.com/" },
        ],
      },
      {
        name: "办公 · 协作",
        links: [
          { name: "飞书", url: "https://www.feishu.cn/" },
          { name: "钉钉", url: "https://www.dingtalk.com/" },
          { name: "企业微信", url: "https://work.weixin.qq.com/" },
          { name: "腾讯会议", url: "https://meeting.tencent.com/" },
          { name: "腾讯文档", url: "https://docs.qq.com/" },
          { name: "腾讯问卷", url: "https://wj.qq.com/" },
          { name: "石墨文档", url: "https://shimo.im/" },
          { name: "WPS云文档", url: "https://www.kdocs.cn/" },
          { name: "Notion", url: "https://www.notion.so/" },
          { name: "语雀", url: "https://www.yuque.com/" },
          { name: "Google Drive", url: "https://drive.google.com/" },
          { name: "Google Docs", url: "https://docs.google.com/" },
          { name: "Gmail", url: "https://mail.google.com/" },
          { name: "Outlook", url: "https://outlook.live.com/" },
          { name: "OneDrive", url: "https://onedrive.live.com/" },
          { name: "Trello", url: "https://trello.com/" },
          { name: "Slack", url: "https://slack.com/" },
        ],
      },
      {
        name: "数据 · 分析",
        links: [
          { name: "伽马数据", url: "https://www.gamadata.com.cn/" },
          { name: "DataEye", url: "https://www.dataeye.com/" },
          { name: "点点数据", url: "https://www.diandian.com/" },
          { name: "七麦数据", url: "https://www.qimai.cn/" },
          { name: "蝉大师", url: "https://www.chandashi.com/" },
          { name: "AppGrowing", url: "https://appgrowing.cn/" },
          { name: "TalkingData", url: "https://www.talkingdata.com/" },
          { name: "QuestMobile", url: "https://www.questmobile.com.cn/" },
          { name: "巨量算数", url: "https://index.oceanengine.com/" },
          { name: "百度指数", url: "https://index.baidu.com/" },
          { name: "友盟+", url: "https://www.umeng.com/" },
          { name: "神策数据", url: "https://www.sensorsdata.cn/" },
          { name: "GrowingIO", url: "https://www.growingio.com/" },
          { name: "SteamDB", url: "https://steamdb.info/" },
          { name: "VG Insights", url: "https://vginsights.com/" },
        ],
      },
      {
        name: "实用工具",
        links: [
          { name: "一个木函", url: "https://ol.woobx.cn/" },
          { name: "在线工具箱", url: "https://tool.browser.qq.com/" },
          { name: "菜鸟工具", url: "https://c.runoob.com/" },
          { name: "JSON在线工具", url: "https://www.json.cn/" },
          { name: "百度翻译", url: "https://fanyi.baidu.com/" },
          { name: "讯飞听见", url: "https://www.iflyrec.com/" },
          { name: "谷歌翻译", url: "https://translate.google.com/" },
          { name: "DeepL", url: "https://www.deepl.com/translator" },
          { name: "缩略词复原", url: "https://lab.magiconch.com/nbnhhsh/" },
          { name: "二维码生成器", url: "https://cli.im/text" },
          { name: "迅捷PDF", url: "https://app.xunjiepdf.com/" },
          { name: "格式转换", url: "https://convertio.co/zh/" },
          { name: "PDF工具箱", url: "https://www.ilovepdf.com/zh-cn" },
          { name: "图片工具箱", url: "https://www.iloveimg.com/zh-cn" },
          { name: "网络测速", url: "https://www.speedtest.net/" },
          { name: "VirusTotal", url: "https://www.virustotal.com/" },
        ],
      },
      {
        name: "设计 · 创作",
        links: [
          { name: "即时设计", url: "https://js.design/" },
          { name: "创客贴", url: "https://www.chuangkit.com/" },
          { name: "稿定设计", url: "https://www.gaoding.com/" },
          { name: "Figma", url: "https://www.figma.com/" },
          { name: "Canva", url: "https://www.canva.com/" },
          { name: "Photopea", url: "https://www.photopea.com/" },
          { name: "Excalidraw", url: "https://excalidraw.com/" },
          { name: "Miro", url: "https://miro.com/" },
          { name: "站酷", url: "https://www.zcool.com.cn/" },
          { name: "花瓣", url: "https://huaban.com/" },
          { name: "Unsplash", url: "https://unsplash.com/" },
          { name: "Pexels", url: "https://www.pexels.com/" },
          { name: "Iconfont", url: "https://www.iconfont.cn/" },
          { name: "Flaticon", url: "https://www.flaticon.com/" },
          { name: "Coolors", url: "https://coolors.co/" },
          { name: "Remove.bg", url: "https://www.remove.bg/zh" },
          { name: "TinyPNG", url: "https://tinypng.com/" },
        ],
      },
      {
        name: "资讯 · 阅读",
        links: [
          { name: "游戏葡萄", url: "https://youxiputao.com/" },
          { name: "游戏陀螺", url: "https://www.youxituoluo.com/" },
          { name: "GameLook", url: "https://www.gamelook.com.cn/" },
          { name: "触乐", url: "https://www.chuapp.com/" },
          { name: "17173", url: "https://www.17173.com/" },
          { name: "游民星空", url: "https://www.gamersky.com/" },
          { name: "少数派", url: "https://sspai.com/" },
          { name: "36氪", url: "https://36kr.com/" },
          { name: "IT之家", url: "https://www.ithome.com/" },
          { name: "知乎热榜", url: "https://www.zhihu.com/hot" },
          { name: "微博热搜", url: "https://s.weibo.com/top/summary" },
          { name: "游戏产业网", url: "https://www.cgigc.com.cn/" },
          { name: "GamesIndustry.biz", url: "https://www.gamesindustry.biz/" },
          { name: "GamesBeat", url: "https://gamesbeat.com/" },
          { name: "PocketGamer.biz", url: "https://www.pocketgamer.biz/" },
          { name: "Hacker News", url: "https://news.ycombinator.com/" },
          { name: "TechCrunch", url: "https://techcrunch.com/" },
          { name: "The Verge", url: "https://www.theverge.com/" },
          { name: "澎湃新闻", url: "https://www.thepaper.cn/" },
          { name: "央视新闻", url: "https://news.cctv.com/" },
        ],
      },
      {
        name: "影音 · 娱乐",
        links: [
          { name: "哔哩哔哩", url: "https://www.bilibili.com/" },
          { name: "抖音", url: "https://www.douyin.com/" },
          { name: "小红书", url: "https://www.xiaohongshu.com/" },
          { name: "西瓜视频", url: "https://www.ixigua.com/" },
          { name: "YouTube", url: "https://www.youtube.com/" },
          { name: "Twitch", url: "https://www.twitch.tv/" },
          { name: "腾讯视频", url: "https://v.qq.com/" },
          { name: "爱奇艺", url: "https://www.iqiyi.com/" },
          { name: "优酷", url: "https://www.youku.com/" },
          { name: "芒果TV", url: "https://www.mgtv.com/" },
          { name: "网易云音乐", url: "https://music.163.com/" },
          { name: "QQ音乐", url: "https://y.qq.com/" },
          { name: "豆瓣", url: "https://www.douban.com/" },
        ],
      },
      {
        name: "其它 · 关于",
        links: [
          { name: "国家新闻出版署", url: "https://www.nppa.gov.cn/" },
          { name: "中国音数协游戏工委", url: "https://www.cgigc.com.cn/" },
          { name: "中国版权保护中心", url: "https://www.ccopyright.com.cn/" },
          { name: "Glenn GitHub", url: "https://github.com/glennlee1" },
          { name: "本站源码", url: "https://github.com/glennlee1/glenn-s" },
          { name: "百度指数", url: "https://index.baidu.com/" },
          { name: "巨量算数", url: "https://index.oceanengine.com/" },
          { name: "QuestMobile", url: "https://www.questmobile.com.cn/" },
          { name: "网络测速", url: "https://www.speedtest.net/" },
          { name: "实时航班", url: "https://zh.flightaware.com/live/" },
          { name: "天气查询", url: "https://weather.com/zh-CN/" },
          { name: "高德地图", url: "https://www.amap.com/" },
          { name: "谷歌地图", url: "https://www.google.com/maps/" },
          { name: "网页时光机", url: "https://web.archive.org/" },
          { name: "反馈建议", url: "https://github.com/glennlee1/glenn-s/issues" },
        ],
      },
    ],
  };
})();
